let ADMIN="";function $(id){return document.getElementById(id)}function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function adminLogin(){ADMIN=$("password").value;await loadAdmin()}
async function loadAdmin(){let r=await fetch("/api/admin/all",{headers:{"x-admin-password":ADMIN}});if(r.status===401){$("loginMsg").textContent="❌ Wrong password";return}let d=await r.json();$("login").classList.add("hidden");$("panel").classList.remove("hidden");let t=d.tournament,p=d.payment,rm=d.room,f=$("settings");["name","status","description","date","time","timezone","entryFee","prizePool","maxTeams","deadline"].forEach(k=>f.elements[k].value=t[k]??"");f.elements.bkash.value=p.bkash;f.elements.nagad.value=p.nagad;f.elements.bkashEnabled.checked=p.bkashEnabled;f.elements.nagadEnabled.checked=p.nagadEnabled;f.elements.roomId.value=rm.id;f.elements.roomPassword.value=rm.password;f.elements.roomPublished.checked=rm.published;$("rules").value=(d.rules||[]).join("\n");
$("topups").innerHTML=d.topups.length?d.topups.map(x=>`<div class="admin-row"><div class="actions"><button class="mini" onclick="topupStatus(${x.id},'Approved')">Approve</button><button class="mini danger" onclick="topupStatus(${x.id},'Rejected')">Reject</button></div><b>${esc(x.player)}</b> • ${esc(x.method)} • ৳${esc(x.amount)}<br>TXID: ${esc(x.txid)} • ${esc(x.status)}</div>`).join(""):"No top-up requests.";
$("adminTeams").innerHTML=d.teams.length?d.teams.map(x=>`<div class="admin-row"><div class="actions"><button class="mini" onclick="teamStatus(${x.id},'${x.status==="Approved"?"Pending":"Approved"}')">${x.status==="Approved"?"Set Pending":"Approve"}</button><button class="mini danger" onclick="deleteTeam(${x.id})">Delete</button></div><b>${esc(x.team_name)}</b> • ${esc(x.status)}<br>Captain: ${esc(x.captain_name)} • ${esc(x.phone)}<br>Players: ${[x.player1,x.player2,x.player3,x.player4,x.player5].map(esc).join(" • ")}</div>`).join(""):"No teams registered.";
$("adminResults").innerHTML=(d.results||[]).map(x=>`<div class="result-row"><span>${esc(x.team)} — Pos ${esc(x.position)}, Kills ${esc(x.kills)}, Points ${esc(x.points)}</span><button class="mini danger" onclick="deleteResult(${x.id})">Delete</button></div>`).join("")}
$("settings").addEventListener("submit",async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target));b.bkashEnabled=e.target.elements.bkashEnabled.checked;b.nagadEnabled=e.target.elements.nagadEnabled.checked;b.roomPublished=e.target.elements.roomPublished.checked;b.rules=$("rules").value;let r=await fetch("/api/admin/save",{method:"POST",headers:{"Content-Type":"application/json","x-admin-password":ADMIN},body:JSON.stringify(b)});$("saveMsg").textContent=r.ok?"✅ Saved successfully.":"❌ Save failed";loadAdmin()});
$("resultForm").addEventListener("submit",async e=>{e.preventDefault();let r=await fetch("/api/admin/results",{method:"POST",headers:{"Content-Type":"application/json","x-admin-password":ADMIN},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(r.ok)e.target.reset();loadAdmin()});
async function topupStatus(id,status){await fetch("/api/admin/topups/"+id+"/status",{method:"POST",headers:{"Content-Type":"application/json","x-admin-password":ADMIN},body:JSON.stringify({status})});loadAdmin()}
async function teamStatus(id,status){await fetch("/api/admin/teams/"+id+"/status",{method:"POST",headers:{"Content-Type":"application/json","x-admin-password":ADMIN},body:JSON.stringify({status})});loadAdmin()}
async function deleteTeam(id){if(confirm("Delete team?")){await fetch("/api/admin/teams/"+id,{method:"DELETE",headers:{"x-admin-password":ADMIN}});loadAdmin()}}
async function deleteResult(id){if(confirm("Delete result?")){await fetch("/api/admin/results/"+id,{method:"DELETE",headers:{"x-admin-password":ADMIN}});loadAdmin()}}