function $(id){return document.getElementById(id)}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0);refreshData()}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function refreshData(){try{const d=await(await fetch("/api/public")).json(),t=d.tournament,r=d.room,p=d.payment;
$("status").textContent=t.status;$("name").textContent=t.name;$("desc").textContent=t.description;$("date").textContent=t.date;$("time").textContent=t.time;$("fee").textContent=t.entryFee;$("prize").textContent=t.prizePool;
$("roomId").textContent=r.published&&r.id?r.id:"HIDDEN";$("roomPass").textContent=r.published&&r.password?r.password:"HIDDEN";$("roomText").textContent=r.published?"Room is published.":"Room details will be published by Admin.";
const nums=[p.bkashEnabled?"bKash: "+p.bkash:"",p.nagadEnabled?"Nagad: "+p.nagad:""].filter(Boolean).join(" • ");$("paymentNumbers").textContent=nums||"Payment methods unavailable";$("walletNumbers").textContent=nums||"Payment methods unavailable";
$("method").innerHTML=(p.bkashEnabled?'<option value="bKash">bKash</option>':"")+(p.nagadEnabled?'<option value="Nagad">Nagad</option>':"");
$("registerFee").textContent=t.entryFee;
$("details").innerHTML=`<div><span>📅 DATE</span><b>${esc(t.date)}</b></div><div><span>⏰ TIME</span><b>${esc(t.time)}</b></div><div><span>🌍 TIME ZONE</span><b>${esc(t.timezone)}</b></div><div><span>📌 DEADLINE</span><b>${esc(t.deadline)}</b></div><div><span>💰 ENTRY FEE</span><b>${esc(t.entryFee)}</b></div><div><span>🏆 PRIZE POOL</span><b>${esc(t.prizePool)}</b></div><div><span>👥 MAX TEAMS</span><b>${esc(t.maxTeams)}</b></div><div><span>🟢 STATUS</span><b>${esc(t.status)}</b></div>`;$("tourDesc").textContent=t.description;
$("rulesList").innerHTML=(d.rules||[]).map(x=>`<li>${esc(x)}</li>`).join("");
const teams=d.teams||[];$("homeTeams").innerHTML=teams.length?teams.slice(0,12).map(x=>`<div class="chip">👥 ${esc(x.team_name)} • ${esc(x.status)}</div>`).join(""):"No teams registered yet.";
$("teamsList").innerHTML=teams.length?teams.map(x=>`<div class="team"><span class="team-status">${esc(x.status)}</span><b>👥 ${esc(x.team_name)}</b></div>`).join(""):"No teams registered yet.";
const rs=(d.results||[]).slice().sort((a,b)=>(+b.points)-(+a.points));$("resultsRows").innerHTML=rs.length?rs.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.team)}</td><td>${esc(x.kills)}</td><td><b>${esc(x.points)}</b></td></tr>`).join(""):'<tr><td colspan="4">No results yet.</td></tr>'}catch(e){console.error(e)}}
$("registerForm").addEventListener("submit",async e=>{e.preventDefault();const r=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}),d=await r.json();$("registerMsg").textContent=r.ok?"✅ Registration successful!":"❌ "+d.error;if(r.ok)e.target.reset();refreshData()});
$("walletForm").addEventListener("submit",async e=>{e.preventDefault();const r=await fetch("/api/topup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}),d=await r.json();$("walletMsg").textContent=r.ok?"✅ Top-up request submitted.":"❌ "+d.error;if(r.ok)e.target.reset()});
refreshData();